version: 1.0

# 构建 MkDocs 文档
mkdocs:
  configuration: mkdocs.yml  # 指定你的 mkdocs 配置文件路径
  fail_on_warning: false     # 是否在出现警告时使构建失败

# 构建环境配置
build:
  os: ubuntu-22.04          # 构建操作系统
  tools:
    python: "3.10"          # Python 版本

# Python 依赖项
python:
  install:
    - requirements: docs/requirements.txt  # 指定包含 MkDocs 及其插件的依赖文件

# 可选配置
formats: []  # 构建输出格式，默认 HTML 不需要指定

# 构建作业配置
sphinx:
  configuration: null       # 不使用 Sphinx
