site_name: BNBU-FM课程攻略
theme: readthedocs
repo_url: https://github.com/FM-Course/bnbu-fm-course-sharing 

nav:
  - 首页: index.md
  - 贡献: contribute.md
  - 收录课程名录: list.md
  - 致谢: thanks.md
  - Major Require:
    - Calculus I: Calculus-I.md
    - Linear Algebra I: Linear-Algebra-I.md
    - Principles of Accounting I: Principles-of-Accounting-I.md
    - Calculus II: Calculus-II.md
    - Linear Algebra II: Linear-Algebra-II.md
    - C++ Programming Language: C++-Programming-Language.md
    - Ordinary Differential Equations: Ordinary-Differential-Equations.md
    - Introdction to Finance: Introdction-to-Finance.md
    - Probability Theory: Probability-Theory.md
    - Mathematical Statistics: Mathematical-Statistics.md
    - Data Structure: Data-Structure.md
    - Advanced Financial Mathematics: Advanced-Financial-Mathematics.md
    - Applied Stochastic Process: Applied-Stochastic-Process.md
    - Financial Mathematics: Financial-Mathematics.md
    - Introduction to Econometrics: Introduction-to-Econometrics.md
    - Investments: Investments.md
    - Macroeconomics: Macroeconomics.md
    - Microeconomics: Microeconomics.md
    - Risk Management in Finance: Risk-Management-in-Finance.md
    - Time Series for Finance and Macroeconomics: Time-Series-for-Finance-and-Macroeconomics.md
